### ISSUE TITLE
504 (Timeout) error when logging in: Not returning to login mask

### ISSUE THREAD

**Issue by MrCustomizer** [MrCustomizer/palaver#37]
MTRNord reports, that the app gets stuck on the spinner when the login process hits a timeout because of a slow server.

**Comment by MTRNord** [comment]
Server I am using: matrix.ffslfl.net (if it matters)

**Comment by MrCustomizer** [comment]
This should behave differently now and at least return to the login mask after the timeout has occurred. Doesn't solve the underlying problem, though.

**Comment by MrCustomizer** [comment]
MTRNord: Is this error still happening? I've tried to reproduce it on latest master by setting the connection timeout to a very low value but had no luck.

**Comment by MTRNord** [comment]
I will try again with the newewst Master :)

**Comment by MTRNord** [comment]
It still fails and again doesn't go back to the login mask anymore too
